name: semaphore
version: 1.0.0
description: Semaphore is lightweight data type that is used for controlling the cooperative access to a common resource inside the isolate.
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
