name: semaphore
version: 1.0.0
description: Lightweight implementation of a semaphore, a condition variable, and a lock that can be used to control (synchronize) access to a shared resources within an isolate.
repository: https://github.com/mezoni/semaphore
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
